- project:
    templates:
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - storlets-functional
        - storlets-functional-podman
        - storlets-functional-centos-9-stream
    gate:
      jobs:
        - storlets-functional

- job:
    name: storlets-functional
    pre-run: playbooks/storlets-functional/pre.yaml
    run: playbooks/storlets-functional/run.yaml
    post-run: playbooks/storlets-functional/post.yaml
    nodeset: ubuntu-noble
    timeout: 2400
    irrelevant-files:
      - ^api-ref/.*$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^.gitignore$
      - ^.gitreview$
      - ^.mailmap$
      - ^AUTHORS$
      - ^CHANGELOG$
      - ^README.rst$
      - ^tests/unit/.*$
    vars:
      storlets_gateway_module: docker

- job:
    name: storlets-functional-podman
    parent: storlets-functional
    voting: false
    vars:
      storlets_gateway_module: podman

- job:
    name: storlets-functional-centos-9-stream
    parent: storlets-functional
    nodeset: centos-9-stream
    voting: false
