#!/bin/bash

status() {
{% raw %}
  state=`docker inspect --format="{{ .State.Running }}" registry`
{% endraw %}
  if [ $? -eq 0 ] && [ $state == 'true' ]; then
     echo docker-registry is running
     return 1
  else
     echo docker-registry not running
     return 0
  fi
}

start() {
  status
  if [ $? -eq 0 ]; then
    docker stop registry &> /dev/null
    docker rm registry &> /dev/null
    docker run --restart unless-stopped -d -p {{ docker_registry_port }}:5000 -v /var/lib/registry:/var/lib/registry --name registry registry:2
    echo docker-registry started
  fi
}

stop() {
  status
  if [ $? -eq 1 ]; then
    docker stop registry &> /dev/null
    docker rm registry &> /dev/null
    echo docker-registry stopped
  fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
